# Generated by Django 5.2.7 on 2025-10-31 02:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('ultimo_costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LineaArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompraCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_id', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listas.articulo')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listas.grupoarticulo'),
        ),
        migrations.AddField(
            model_name='grupoarticulo',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listas.lineaarticulo'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listas.lineaarticulo'),
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('promocion', 'Promoción'), ('mayoreo', 'Mayoreo')], default='normal', max_length=50)),
                ('canal', models.CharField(choices=[('web', 'Web'), ('tienda', 'Tienda'), ('distribuidor', 'Distribuidor'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('vigente', 'Vigente'), ('inactiva', 'Inactiva')], default='borrador', max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='listas.empresa')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CombinacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('articulos', models.ManyToManyField(related_name='combinaciones', to='listas.articulo')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones', to='listas.listaprecio')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='listas.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='listas.sucursal'),
        ),
        migrations.CreateModel(
            name='PrecioArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('autorizado_bajo_costo', models.BooleanField(default=False)),
                ('motivo_bajo_costo', models.TextField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='listas.articulo')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_articulo', to='listas.listaprecio')),
            ],
            options={
                'unique_together': {('lista', 'articulo')},
            },
        ),
        migrations.CreateModel(
            name='ReglaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('canal', 'Canal'), ('escala_unidades', 'Escala de Unidades'), ('escala_monto', 'Escala de Monto'), ('combinacion', 'Combinación de Productos'), ('monto_pedido', 'Monto de Pedido'), ('descuento_proveedor', 'Descuento del Proveedor')], max_length=50)),
                ('prioridad', models.PositiveIntegerField(default=100)),
                ('activo', models.BooleanField(default=True)),
                ('canal', models.CharField(blank=True, choices=[('web', 'Web'), ('tienda', 'Tienda'), ('distribuidor', 'Distribuidor'), ('otro', 'Otro')], max_length=50, null=True)),
                ('min_unidades', models.PositiveIntegerField(blank=True, null=True)),
                ('max_unidades', models.PositiveIntegerField(blank=True, null=True)),
                ('min_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listas.articulo')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listas.grupoarticulo')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listas.lineaarticulo')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='listas.listaprecio')),
            ],
            options={
                'ordering': ['prioridad'],
                'unique_together': {('lista', 'tipo', 'prioridad', 'canal')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='listaprecio',
            unique_together={('empresa', 'sucursal', 'nombre', 'fecha_inicio')},
        ),
    ]
