# Generated by Django 5.2.7 on 2025-10-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinacionproducto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='combinacionproducto',
            name='minimo_por_articulo',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad mínima por cada artículo de la combinación'),
        ),
        migrations.AddField(
            model_name='combinacionproducto',
            name='tipo_aplicacion',
            field=models.CharField(choices=[('descuento_pct', 'Descuento %'), ('precio_fijo', 'Precio fijo por artículo')], default='descuento_pct', max_length=20),
        ),
    ]
